### ISSUE TITLE
Add Examples Section to all Class Documentation

### ISSUE THREAD

**Issue by gmischl1** [neurodata/mvlearn#111]
## Expected Behavior
To make documentation more helpful for people who want quick example usage without having to parse through long tutorial notebooks, have a quick example section in the docstring for each class.

## Actual Behavior
Currently, only a couple classes have this.

**Comment by achang63** [comment]
Ok, I'll add some to the clustering algorithms in the next week.

**Comment by gmischl1** [comment]
> Ok, I'll add some to the clustering algorithms in the next week.

Don't worry, I added them to all classes that aren't currently in open PR's. But feel free to check them and edit this PR if you want to change them for clustering.
https://github.com/neurodata/mvlearn/pull/109/files
