### ISSUE TITLE
Please develop a conda feedstock

### ISSUE THREAD

**Issue by gdevenyi** [neurodata/mvlearn#124]
Please develop a conda feedstock for conda-forge.

Thanks :+1:

**Comment by gdevenyi** [comment]
https://conda-forge.org/#add_recipe

**Comment by gmischl1** [comment]
Thanks for the suggestion! That's a great idea, and we will work on adding it as soon as possible so we can roll it out with the next big version that will be going on PyPi.

**Comment by gmischl1** [comment]
PR is currently up on staged-recipes, waiting for review https://github.com/conda-forge/staged-recipes/pull/11383

**Comment by gmischl1** [comment]
mvlearn is now on conda-forge feedstocks!

https://github.com/conda-forge/mvlearn-feedstock

**Comment by gdevenyi** [comment]
Thanks so much!
