### ISSUE TITLE
mimic sklearn datasets API with ours

### ISSUE THREAD

**Issue by rflperry** [neurodata/mvlearn#177]
to what extent we can, parameter names etc. Verify this at least.

**Comment by achang63** [comment]
Should we have the load_UCImultifeature function return a dict-like object like the sklearn data_loaders? This will require us to change and rerun a lot of the tutorials and example doc strings, but the resulting dictionary object can provide users with a lot of useful attributes and metadata associated with the dataset.

**Comment by gmischl1** [comment]
Yeah we probably should allow dictionary output (though still with a return_Xs_y argument so you can get just (Xs, y)). I see that sklearn has the dictionary as the default, I guess we could have the return_Xs_y default to True so we don't have to change all the tutorials. @achang63, @rflperry what are your thoughts? Should the dictionary or the Xs, y be the default?

**Comment by rflperry** [comment]
I'm fine with doing `return_Xs_y` as the default so that tutorials etc. don't have to change. 

FYI this issue also corresponded to the gaussian_mixture function which could better be modified to mimic [make blobs](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_blobs.html)

**Comment by achang63** [comment]
Ok, I like that idea. I'll make return_Xs_y the default but give the option to the return the dictionary.
