### ISSUE TITLE
Explore Multiview Brain Data

### ISSUE THREAD

**Issue by cameronfr** [neurodata/mvlearn#79]
I'd like to explore data where there are two views, and one is data from the brain. I want to think about the ideal theoretical function that could transform one view to the other.

Datasets:
**MindBrainBody**:     
15 minute resting MRI <-----> results of various psychological tests

**Simulated**: 
random image data <-----> some complex function of the random image data

**Andreas Tolias [Paper](https://arxiv.org/abs/1911.05072)**: 
5100 Imagenet 32x64 images <-----> mouse response at 8000 neurons (two-photon imaging) in a couple of mice

I think the last two are the most promising for finding some relationship. I'll have to see if I can get the Tolias data, so right now the simulated data looks most promising.

For the simulated data, one end of the spectrum is cryptographic functions. At other side of the spectrum is linear functions.

**Comment by cameronfr** [comment]
A more concrete idea of what might be interesting:

Given a view `X` and a view `Y` where`Y=f(X)` but the function `f` is unknown

When is it possible to learn a function `f'`  given a lot of data `X` and `Y` , where learning `f'` would mean equal outputs  for `f(x)` and  `f'(x)` on held-out `X`s?

For example let `f` be the first 15 layers of `VGG16`. `X` is the input image, `Y` is the activations of the 15th layer of `VGG16(x)`. Given this paired data, what sort of NN (e.g. what filter sizes, number of layers, etc -- architectures) can learn the original function?

Another way of asking this specific question is: when can `network A` be successfully [distilled](https://arxiv.org/pdf/1503.02531.pdf) into `network B`

And maybe answering this question will help give insight into: When / with what architectures can `stimululus X` and `neuronal response Y` be modeled with a CNN/DNN .

**Comment by bdpedigo** [comment]
These sound like interesting questions but I'm worried they are not concrete enough for the class/sprint 1. Need to propose some actual experiments and what the output of those experiments will be; what is the thing you are sure you can get done by end of sprint 1 that we will be able to evaluate.

**Comment by cameronfr** [comment]
New issue is to implement [SGPLVMs](https://www.google.com/url?q=http://www.robots.ox.ac.uk/~phst/Theses/ek%2520thesis.pdf&sa=U&ved=2ahUKEwjnlomFxdfnAhVVYTUKHbYXBVkQFjABegQIExAB&usg=AOvVaw2iXOMf4a1umLSH5Ke4XsTy) -- a multiview embedding method. Specifically I will reimplement in python and reproduce figure 5.1 -- metrics on the pose dataset.

**Comment by jovo** [comment]
ok, that is concrete! i don't know why we would want that in our package? can you elaborate?
i liked your prior plan of applying multivariate regression to data :)

**Comment by cameronfr** [comment]
I think GPLVMs have a nice idea of a function prior and I think it'd be cool to have a multiview version of that. I'm not sure how much the multiview version adds to the standard GPLVM, though. For multivariate regression I don't know of a specific algorithm to implement that is guaranteed to work on the specific data (~2000 pixels values => ~8000 neuron values, 5100 of these data points)

**Comment by jovo** [comment]
random forest.
"cool" isn't a particular compelling problem to solve.  
we have many multiview algorithms already, adding another should be based on it solves a problem that the others don't.  
if GPLVM does, great, tell us what that problem is?

**Comment by cameronfr** [comment]
It seems like the standard GPLVM is good for ["trajectory inference"](https://en.wikipedia.org/wiki/Trajectory_inference) which is taking gene expression measurements from growing cells and reducing the (time, many gene expressions) to (psuedotime, single branching latent) that shows how the cells take different paths other time. I don't know if the multiview version extends naturally / meaningfully to that, though.

If I try to apply random forests to Tolias data, what would a valid Issue be? Applying different RF methods like SPORF and documenting how well they do? Or re-implementing some RF method for which there is no python code yet and running it on the data (do you know of any such RF methods?).
