### ISSUE TITLE
Implement Multi-view Spherical KMeans

### ISSUE THREAD

**Issue by achang63** [neurodata/mvlearn#82]
This algorithm is very similar to multi-view kmeans and much of the code has already been implemented on a jupyter notebook. Furthermore, the implementation has been verified by replicating some results from the corresponding paper. As such, it would make sense to clean up the code, add unit tests, perform additional validation, and add it to the package.

For validating the algorithm, I will be recreating the second half of Figure 3 from the Multi-view Clustering Paper written by Bickel and Scheffer. I will also be comparing the performance of the multi-view algorithm against the single-view spherical kmeans algorithm on simulated data using similar cases as the validation performed on multi-view kmeans. 

Link to the paper: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.66.312&rep=rep1&type=pdf

**Comment by bdpedigo** [comment]
Can you briefly describe what figures/tables from the paper you plan on recreating, or benchmarks against implementations, so that we know how to evaluate success at end of Sprint 1?
