### ISSUE TITLE
Implement Jive

### ISSUE THREAD

**Issue by akoul1** [neurodata/mvlearn#87]
- Write a useful implementation of JIVE and add to package
- Have code and validation notebooks PRed
- Based on Algorithm outlined here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3671601/
- Modeling off of code can be found here: https://genome.unc.edu/jive/

**Comment by bdpedigo** [comment]
Jive will be merged or PRed by end of sprint 1? I'd also make a plan for which figures/tables from the paper you will recreate or which existing implementations you can compare to. Make sure that you have the data/sim parameters in order to be able to verify.

**Comment by akoul1** [comment]
Hey Pedigo, sorry for not seeing this earlier. I plan on getting it PR'ed. There are probably some things I will want to add after as it is a pretty expansive algorithm (and I'm still pretty new to the writing tests thing). As for figures, I am going to make simulated data as described in the above paper
